# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Armando Fox
subtitle: A breadth-first traversal of life
email: fox@berkeley.edu
description: >- # this means to ignore newlines until "baseurl:"
  Armando Fox's personal website: blog, reviews, screeds, advice, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://armandofox.comv" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  armandofox

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.23.0
# theme: minima
plugins:
  - jekyll-include-cache
  - jekyll-feed

include: ["_pages", "_posts"]

breadcrumbs: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: ""
      type: posts, pages
      sidebar:
        - title: "Travel"
          image: /assets/img/piano.jpg
          text: >
            **Sep 11-12:** Tapia Conference, Dallas, TX
            **Sep 22-26:** Univ. of Sao Paulo and CBSOFT, Recife, Brasil
            **Oct 20-26:** ACM CompEd, Gaborone, Botswana
            **Dec 1-12:** Out of office (personal)
    values:
      layout: single
